server:
  port: 6443
  servlet:
    context-path: /apiService
spring:
  servlet:
    multipart:
      enabled: true #是否启用http上传处理
      max-request-size: 1000MB #最大请求文件的大小
      max-file-size: 200MB #设置单个文件最大长度
      file-size-threshold: 20MB #当文件达到多少时进行磁盘写入